# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lin
    username: lin
    password: ZLY34z3SMX3yiGc3
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    # 所有访问都经过静态资源路径
#    static-path-pattern: /**
  resources:
    # 为我们工程中的资源文件建立映射
    add-mappings: false
    # 配置静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

# Mybatis配置
mybatis:
  # 配置为 com.example.restfulapi.bean 指向实体类包路径。
  type-aliases-package: com.example.restfulapi.bean
  # 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件。
  mapper-locations: classpath\:mapper/*.xml
server:
  servlet:
    context-path: /api
  port: 8081

# 自定义参数
pre-read:
  debug: true
  # 图片上传路径
  # uploadPath: E:/upload/
  uploadPath: /www/wwwroot/java/upload/
  # 不需要验证的方法路径，用<,>隔开
  ignorePath: /aaa
  # 允许访问的路径
  allowOrigin: http://vue.linwenjin.top,http://localhost:8080