# 数据源配置
spring:
  datasource:
    name: lin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/lin
      username: lin
      password: ZLY34z3SMX3yiGc3
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  mvc:
    # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    # 所有访问都经过静态资源路径
#    static-path-pattern: /**
  resources:
    # 为我们工程中的资源文件建立映射
    add-mappings: false
    # 配置静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.example.bean  # 注意：对应实体类的路径
server:
  servlet:
    context-path: /api
  port: 8081

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#打印出生成的sql语句
logging:
  level:
    com:
      example:
        mybatis:
          dao: debug

# 自定义参数
pre-read:
  debug: true
  # 图片上传路径
  # uploadPath: E:/upload/
  uploadPath: /www/wwwroot/java/upload/
  # 不需要验证的方法路径，用<,>隔开
  ignorePath: /aaa
  # 允许访问的路径
  allowOrigin: http://vue.linwenjin.top,http://localhost:8080